apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name:  po-sa
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["*"]
